spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: smileroom28806
    password: oegvtgoowlpxptuy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/backend
    username: postgres
    password: syspass
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 5MB

---

app:
  token:
    secret: ArlakMySecretIsTheBest
    issuer: BackenService

  email:
    from: smileroom28806@gmail.com
